server:
  port: 8091

spring:
  application:
    name: bus-inventory-service
  datasource:
    username: TICKETBOOKINGS
    password: sarasu10
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
