server:
  port: 8095

spring:
  application:
    name: api-gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  register-with-eureka: true
  fetch-registry: true